# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQT5_Ex1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from AssnCL22_Classes import *


class Ui_MainWindow(object):
    # Definitions
    # =====================================================================
    def __init__(self):
        self.product1 = Laptop("MacBook Air", 705, "Apple", "US", "8 GB", "Core I5", "13.3 inch")
        self.product2 = Laptop("Swift", 528, "ACER", "Taiwan", "4 GB", "N6000 Quad Core", "14 inch")
        self.product3 = Laptop("Pavillion", 479, "HP", "US", "4 GB", "AMD", "15.6 inch")
        self.product4 = Car("Micra", 21000, "Nissan", "Japan", "1000 CC", "5", "3");
        self.product5 = Car("Focus", 26000, "Ford", "US", "1400 CC", "5", "4")
        self.product6 = Car("Touran", 29000, "VW", "German", "1700 CC", "7", "5")
        self.product7 = Book("Java First", 30, "O'Reilly", "UK", "Intro to Java", "Sierra & Bates", "Technical")
        self.product8 = Book("Promised Land", 40, "Crown", "Us", "Political Memoir", "B.Obama", "Biography")
        self.productList = [self.product1, self.product2, self.product3, self.product4,
                            self.product5, self.product6, self.product7, self.product8]
        self.current=0  # current product

        self.product = self.productList[0]  # initialize to first student

    # ========= End of Definitions ============================



    # ========= Display Current Product ============================
    def display(self,index):
        self.product = self.productList[index]
        self.lineEdit1.setText(str(self.product.readName()))
        self.lineEdit2.setText(str(self.product.readPrice()))
        self.lineEdit3.setText(str(self.product.readCompany()))
        self.lineEdit4.setText(str(self.product.readHeadquarters()))
        self.lineEdit5.setText(str(self.product.readOrdered()))
        type= self.product.readType()
        self.comboBox1.setCurrentText(type)
        available = self.product.readAvailable()
        if (available == True):
            self.checkBox1.setChecked(True)
        else:
            self.checkBox1.setChecked(False)
        self.lineEdit6.setText(str(self.product.readDescriptionPart1()))
        self.lineEdit7.setText(str(self.product.readDescriptionPart2()))
        self.lineEdit8.setText(str(self.product.readDescriptionPart3()))

    # ========= End of  Display Product ============================



    # ========= Event Handling Methods ============================
    def nextEvent(self):
        if (self.current < (len(self.productList) - 1)):
            self.current += 1
            self.display(self.current)

    def prevEvent(self):
        if (self.current >0):
            self.current -= 1
            self.display(self.current)

    def firstEvent(self):
        self.current = 0
        self.display(self.current)

    def lastEvent(self):
        self.current = len(self.productList) - 1
        self.display(self.current)

    def exitEvent(self):
        exit()

    def markAvailEvent(self):
        self.product.markAvailable()
        self.display(self.current)

    def markUnavailEvent(self):
        self.product.markUnavailable()
        self.display(self.current)
    def clearEvent(self):
        self.lineEdit1.setText('')
        self.lineEdit2.setText('')
        self.lineEdit3.setText('')
        self.lineEdit4.setText('')
        self.lineEdit5.setText('')
        self.comboBox1.setCurrentText('Laptop')
        self.checkBox1.setChecked(True)
        self.lineEdit6.setText('')
        self.lineEdit7.setText('')
        self.lineEdit8.setText('')
    def insertEvent(self):

        name = self.lineEdit1.text()
        price = int(self.lineEdit2.text())
        make = self.lineEdit3.text()
        location = self.lineEdit4.text()
        description1 = self.lineEdit6.text()
        description2 = self.lineEdit7.text()
        description3 = self.lineEdit8.text()
        newType = self.comboBox1.currentText()
        newProduct = Book(name, price, make, location, description1, description2, description3)
        if (newType == 'Laptop'):
            newProduct = Laptop(name, price, make, location, description1, description2, description3)
        elif (newType == 'Car'):
            newProduct = Car(name, price, make, location, description1, description2, description3)

        self.productList.append(newProduct)
        self.display(len(self.productList) - 1)


    def orderEvent(self):
        self.product.stepOrdered()
        self.display(self.current)

    def updateEvent(self):
        newPrice = int(self.lineEdit9.text())
        self.product.setPrice(newPrice)
        self.display(self.current)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(864, 711)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 0, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 70, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 110, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 150, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 190, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(110, 230, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(110, 260, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit1.setGeometry(QtCore.QRect(230, 70, 171, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit1.setFont(font)
        self.lineEdit1.setObjectName("lineEdit1")
        self.lineEdit2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit2.setGeometry(QtCore.QRect(230, 110, 171, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit2.setFont(font)
        self.lineEdit2.setObjectName("lineEdit2")
        self.lineEdit3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit3.setGeometry(QtCore.QRect(230, 150, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit3.setFont(font)
        self.lineEdit3.setObjectName("lineEdit3")
        self.lineEdit4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit4.setGeometry(QtCore.QRect(230, 190, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit4.setFont(font)
        self.lineEdit4.setObjectName("lineEdit4")
        self.lineEdit5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit5.setGeometry(QtCore.QRect(230, 230, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit5.setFont(font)
        self.lineEdit5.setObjectName("lineEdit5")
        self.lineEdit6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit6.setGeometry(QtCore.QRect(60, 340, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit6.setFont(font)
        self.lineEdit6.setObjectName("lineEdit6")
        self.lineEdit7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit7.setGeometry(QtCore.QRect(60, 380, 371, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit7.setFont(font)
        self.lineEdit7.setObjectName("lineEdit7")
        self.lineEdit8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit8.setGeometry(QtCore.QRect(60, 420, 371, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit8.setFont(font)
        self.lineEdit8.setObjectName("lineEdit8")
        self.lineEdit9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit9.setGeometry(QtCore.QRect(240, 600, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit9.setFont(font)
        self.lineEdit9.setObjectName("lineEdit9")
        self.comboBox1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox1.setGeometry(QtCore.QRect(230, 270, 171, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox1.setFont(font)
        self.comboBox1.setObjectName("comboBox1")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.comboBox1.addItem("")
        self.checkBox1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox1.setGeometry(QtCore.QRect(170, 310, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox1.setFont(font)
        self.checkBox1.setObjectName("checkBox1")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(80, 460, 131, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton1.setFont(font)
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(240, 460, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton2.setFont(font)
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton3.setGeometry(QtCore.QRect(80, 500, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton3.setFont(font)
        self.pushButton3.setObjectName("pushButton3")
        self.pushButton4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton4.setGeometry(QtCore.QRect(240, 500, 141, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton4.setFont(font)
        self.pushButton4.setObjectName("pushButton4")
        self.pushButton5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton5.setGeometry(QtCore.QRect(80, 550, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton5.setFont(font)
        self.pushButton5.setObjectName("pushButton5")
        self.pushButton6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton6.setGeometry(QtCore.QRect(240, 550, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton6.setFont(font)
        self.pushButton6.setObjectName("pushButton6")
        self.pushButton7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton7.setGeometry(QtCore.QRect(80, 600, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton7.setFont(font)
        self.pushButton7.setObjectName("pushButton7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 864, 26))
        self.menubar.setObjectName("menubar")
        self.menuAdmin = QtWidgets.QMenu(self.menubar)
        self.menuAdmin.setObjectName("menuAdmin")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFirst = QtWidgets.QAction(MainWindow)
        self.actionFirst.setObjectName("actionFirst")
        self.actionLast = QtWidgets.QAction(MainWindow)
        self.actionLast.setObjectName("actionLast")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionMarkAvail = QtWidgets.QAction(MainWindow)
        self.actionMarkAvail.setObjectName("actionMarkAvail")
        self.actionMarkNotAvail = QtWidgets.QAction(MainWindow)
        self.actionMarkNotAvail.setObjectName("actionMarkNotAvail")
        self.menuAdmin.addAction(self.actionMarkAvail)
        self.menuAdmin.addAction(self.actionMarkNotAvail)
        self.menuAdmin.addAction(self.actionFirst)
        self.menuAdmin.addAction(self.actionLast)
        self.menuAdmin.addAction(self.actionExit)
        self.menubar.addAction(self.menuAdmin.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton1.pressed.connect(self.nextEvent) # type: ignore
        self.pushButton2.pressed.connect(self.prevEvent) # type: ignore
        self.pushButton3.pressed.connect(self.clearEvent) # type: ignore
        self.pushButton4.pressed.connect(self.insertEvent) # type: ignore
        self.pushButton5.pressed.connect(self.orderEvent) # type: ignore
        self.pushButton6.pressed.connect(self.exitEvent) # type: ignore
        self.pushButton7.pressed.connect(self.updateEvent) # type: ignore

        self.actionExit.triggered.connect(self.exitEvent) # type: ignore
        self.actionLast.triggered.connect(self.lastEvent) # type: ignore
        self.actionFirst.triggered.connect(self.firstEvent) # type: ignore
        self.actionMarkAvail.triggered.connect(self.markAvailEvent) # type: ignore
        self.actionMarkNotAvail.triggered.connect(self.markUnavailEvent) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.display(0)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Product Application"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.label_3.setText(_translate("MainWindow", "Price"))
        self.label_4.setText(_translate("MainWindow", "Make"))
        self.label_5.setText(_translate("MainWindow", "Location"))
        self.label_6.setText(_translate("MainWindow", "Ordered"))
        self.label_7.setText(_translate("MainWindow", "Type"))
        self.lineEdit9.setText(_translate("MainWindow", "111"))
        self.comboBox1.setItemText(0, _translate("MainWindow", "Laptop"))
        self.comboBox1.setItemText(1, _translate("MainWindow", "Car"))
        self.comboBox1.setItemText(2, _translate("MainWindow", "Book"))
        self.checkBox1.setText(_translate("MainWindow", "Available"))
        self.pushButton1.setText(_translate("MainWindow", "Next"))
        self.pushButton2.setText(_translate("MainWindow", "Prev"))
        self.pushButton3.setText(_translate("MainWindow", "Clear"))
        self.pushButton4.setText(_translate("MainWindow", "Insert_Item"))
        self.pushButton5.setText(_translate("MainWindow", "Order_Item"))
        self.pushButton6.setText(_translate("MainWindow", "Exit"))
        self.pushButton7.setText(_translate("MainWindow", "Update_Price"))
        self.menuAdmin.setTitle(_translate("MainWindow", "Admin"))
        self.actionFirst.setText(_translate("MainWindow", "First"))
        self.actionLast.setText(_translate("MainWindow", "Last"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionMarkAvail.setText(_translate("MainWindow", "MarkAvail"))
        self.actionMarkNotAvail.setText(_translate("MainWindow", "MarkNotAvail"))
