# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TransportManagerUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from TestClasses import *


class Ui_MainWindow(object):
    # Definitions
    # =====================================================================
    def __init__(self):
        self.item1 = Fleet("Dylan", "750 per week", "Abnormal", "Tullamore", "Scania S770 (231 OY 132)")
        self.item2 = Fleet("Adam", "700 per week", "Chilled", "Tullamore", "Scania R520 (12 OY 12)")
        self.item3 = Fleet("Jack", "700 per week", "Liquids", "Tullamore", "Volvo FH16 (152 OY 420")
        self.item4 = Truck("N/A", "N/A", "N/A", "Tullamore", "Volvo FMX", "Volvo", "500", "201 KE 50")
        self.item5 = Truck("N/A", "N/A", "N/A", "Tullamore", "Renault Premium", "Renault", "480", "12 KE 200")
        self.item6 = Truck("N/A", "N/A", "N/A", "Tullamore", "DAF XF", "DAF", "560", "09 C 69")
        self.item7 = Driver("Steven", "600 per week", "N/A", "Tullamore", "N/A", "Steven Seagull ", "22", "C1, Wide Loads")
        self.item8 = Driver("John", "700 per week", "N/A", "Tullamore", "N/A", "John Doe", "36", "C1, Chilled, Wide Loads")
        self.item9 = Driver("Darragh", "750 per week", "N/A", "Tullamore", "N/A", "Darragh Counihan", "46", "C1, Liquids, Abnormal")
        self.item10 = Loaded("Dylan", "750 per week", "Abnormal", "Tullamore", "Scania S770 (231 OY 132)", "Lowloader", "Portacabin", "Cork")
        self.item11 = Loaded("Adam", "700 per week", "Chilled", "Tullamore", "Scania R520 (12 OY 12)", "Fridge", "Fresh Fish", "France")

        self.itemList = [self.item1, self.item2, self.item3, self.item4, self.item5, self.item6, self.item7, self.item8,
                         self.item9, self.item10, self.item11]
        self.current = 0

        self.item = self.itemList[0]

    # ========= End of Definitions ============================

    # ========= Display Current Item ============================
    def display(self, index):
        self.item = self.itemList[index]
        self.driverName.setText(str(self.item.readDriverName()))
        self.driverWage.setText(str(self.item.readDriverWage()))
        self.licenceType.setText(str(self.item.readDriverLicence()))
        self.yardLocation.setText(str(self.item.readCompanyYard()))
        self.assignedTruck.setText(str(self.item.readAssignedTruck()))
        type = self.item.readType()
        self.typeComboBox.setCurrentText(type)
        available = self.item.readAvailable()
        if available:
            self.availCheckBox.setChecked(True)
        else:
            self.availCheckBox.setChecked(False)
        self.trailerType.setText(str(self.item.readDescriptionPart1()))
        self.assignedLoad.setText(str(self.item.readDescriptionPart2()))
        self.loadDestination.setText(str(self.item.readDescriptionPart3()))

    # ========= End of  Display Item ============================

    # ========= Event Handling Methods ============================
    def nextEvent(self):
        if self.current < (len(self.itemList) - 1):
            self.current += 1
            self.display(self.current)

    def prevEvent(self):
        if self.current > 0:
            self.current -= 1
            self.display(self.current)

    def exitEvent(self):
        exit()

    def markAvailEvent(self):
        self.item.markAvailable()
        self.display(self.current)

    def markUnavailEvent(self):
        self.item.markUnavailable()
        self.display(self.current)

    def clearEvent(self):
        self.driverName.setText('')
        self.driverWage.setText('')
        self.licenceType.setText('')
        self.yardLocation.setText('')
        self.assignedTruck.setText('')
        self.typeComboBox.setCurrentText('Fleet')
        self.availCheckBox.setChecked(True)
        self.trailerType.setText('')
        self.assignedLoad.setText('')
        self.loadDestination.setText('')

    def insertEvent(self):
        name = self.driverName.text()
        wage = self.driverWage.text()
        licence = self.licenceType.text()
        yard = self.yardLocation.text()
        truck = self.assignedTruck.text()
        description1 = self.trailerType.text()
        description2 = self.assignedLoad.text()
        description3 = self.loadDestination.text()
        newType = self.typeComboBox.currentText()

        if newType == 'Truck':
            self.itemList.append(Truck(name, wage, licence, yard, truck, description1, description2, description3))
        elif newType == 'Driver':
            self.itemList.append(Driver(name, wage, licence, yard, truck, description1, description2, description3))
        elif newType == 'Loaded':
            self.itemList.append(Loaded(name, wage, licence, yard, truck, description1, description2, description3))

        self.display(len(self.itemList) - 1)

    # =======| Testing insert from file |=======
    def insertFromFileEvent(self):
        print("Inserting from file")
        infile = open('input.txt', "r")
        outfile = open('output8.txt', "w")
        line = infile.readline()
        line = infile.readline()
        name = ""
        wage = ""
        licence = ""
        yard = ""
        truck = ""
        type = ""
        desc1 = ""
        desc2 = ""
        desc3 = ""
        for line in infile:
            # TODO: See if I can add multiple entries at once
            # Possibly can be done by inserting to object while in the loop

            list = line.split(", ")

            print(list[0])
            name += list[0]

            print(list[1])
            wage += list[1]

            print(list[2])
            licence += list[2]

            print(list[3])
            yard += list[3]

            print(list[4])
            truck += list[4]

            print(list[5])
            type += list[5]

            print(list[6])
            desc1 += list[6]

            print(list[7])
            desc2 += list[7]

            print(list[8])
            desc3 += list[8]

        name = name
        wage = wage
        licence = licence
        yard = yard
        truck = truck
        newType = type
        description1 = desc1
        description2 = desc2
        description3 = desc3

        print("Type is: "+ newType)

        if newType == 'Truck':
            self.itemList.append(Truck(name, wage, licence, yard, truck, description1, description2, description3))
        elif newType == 'Driver':
            self.itemList.append(Driver(name, wage, licence, yard, truck, description1, description2, description3))
        elif newType == 'Loaded':
            print("Added to Loaded")
            self.itemList.append(Loaded(name, wage, licence, yard, truck, description1, description2, description3))

        self.display(len(self.itemList) - 1)


    def assignLoadEvent(self):
        name = self.driverName.text()
        wage = self.driverWage.text()
        licence = self.licenceType.text()
        yard = self.yardLocation.text()
        truck = self.assignedTruck.text()
        self.availCheckBox.setChecked(False)
        description1 = self.trailerType.text()
        description2 = self.assignedLoad.text()
        description3 = self.loadDestination.text()
        newType = self.typeComboBox.currentText()
        newProduct = Loaded(name, wage, licence, yard, truck, description1, description2, description3)
        self.itemList.append(newProduct)
        self.display(len(self.itemList) - 1)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(452, 699)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(90, 80, 261, 184))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.driverName = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.driverName.setFont(font)
        self.driverName.setObjectName("driverName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.driverName)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.driverWage = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.driverWage.setFont(font)
        self.driverWage.setObjectName("driverWage")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.driverWage)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.licenceType = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.licenceType.setFont(font)
        self.licenceType.setObjectName("licenceType")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.licenceType)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.yardLocation = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.yardLocation.setFont(font)
        self.yardLocation.setObjectName("yardLocation")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.yardLocation)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.assignedTruck = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.assignedTruck.setFont(font)
        self.assignedTruck.setObjectName("assignedTruck")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.assignedTruck)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.typeComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.typeComboBox.setFont(font)
        self.typeComboBox.setObjectName("typeComboBox")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.typeComboBox)
        self.availCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.availCheckBox.setGeometry(QtCore.QRect(160, 270, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.availCheckBox.setFont(font)
        self.availCheckBox.setObjectName("availCheckBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(90, 390, 261, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.insertButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.insertButton.setFont(font)
        self.insertButton.setObjectName("insertButton")
        self.gridLayout.addWidget(self.insertButton, 2, 0, 1, 1)
        self.nextButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nextButton.setFont(font)
        self.nextButton.setObjectName("nextButton")
        self.gridLayout.addWidget(self.nextButton, 0, 0, 1, 1)
        self.prevButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.prevButton.setFont(font)
        self.prevButton.setObjectName("prevButton")
        self.gridLayout.addWidget(self.prevButton, 0, 1, 1, 1)
        self.assignLoadButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.assignLoadButton.setFont(font)
        self.assignLoadButton.setObjectName("assignLoadButton")
        self.gridLayout.addWidget(self.assignLoadButton, 1, 1, 1, 1)
        self.clearButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout.addWidget(self.clearButton, 1, 0, 1, 1)
        self.exitButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.gridLayout.addWidget(self.exitButton, 2, 1, 1, 1)
        self.trailerType = QtWidgets.QLineEdit(self.centralwidget)
        self.trailerType.setGeometry(QtCore.QRect(70, 300, 301, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trailerType.setFont(font)
        self.trailerType.setObjectName("trailerType")
        self.assignedLoad = QtWidgets.QLineEdit(self.centralwidget)
        self.assignedLoad.setGeometry(QtCore.QRect(70, 330, 301, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.assignedLoad.setFont(font)
        self.assignedLoad.setObjectName("assignedLoad")
        self.loadDestination = QtWidgets.QLineEdit(self.centralwidget)
        self.loadDestination.setGeometry(QtCore.QRect(70, 360, 301, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loadDestination.setFont(font)
        self.loadDestination.setObjectName("loadDestination")
        self.insertFromFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.insertFromFileButton.setGeometry(QtCore.QRect(160, 600, 126, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.insertFromFileButton.setFont(font)
        self.insertFromFileButton.setObjectName("insertFromFileButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 452, 26))
        self.menubar.setObjectName("menubar")
        self.menuAdmin = QtWidgets.QMenu(self.menubar)
        self.menuAdmin.setObjectName("menuAdmin")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMark_Available = QtWidgets.QAction(MainWindow)
        self.actionMark_Available.setObjectName("actionMark_Available")
        self.actionMark_Unavailable = QtWidgets.QAction(MainWindow)
        self.actionMark_Unavailable.setObjectName("actionMark_Unavailable")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuAdmin.addAction(self.actionMark_Available)
        self.menuAdmin.addAction(self.actionMark_Unavailable)
        self.menuAdmin.addAction(self.actionExit)
        self.menubar.addAction(self.menuAdmin.menuAction())

        self.retranslateUi(MainWindow)
        self.availCheckBox.pressed.connect(MainWindow.update)  # type: ignore
        self.nextButton.pressed.connect(self.nextEvent)  # type: ignore
        self.prevButton.pressed.connect(self.prevEvent)  # type: ignore
        self.clearButton.pressed.connect(self.clearEvent)  # type: ignore
        self.assignLoadButton.pressed.connect(self.assignLoadEvent)  # type: ignore
        self.actionMark_Unavailable.triggered.connect(self.markUnavailEvent)  # type: ignore
        self.actionMark_Available.triggered.connect(self.markAvailEvent)  # type: ignore
        self.actionExit.triggered.connect(self.exitEvent)  # type: ignore
        self.insertButton.pressed.connect(self.insertEvent)  # type: ignore
        self.exitButton.pressed.connect(self.exitEvent)  # type: ignore
        self.insertFromFileButton.pressed.connect(self.insertFromFileEvent)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Transport Management System"))
        self.label_2.setText(_translate("MainWindow", "Driver"))
        self.driverName.setText(_translate("MainWindow", "Dylan"))
        self.label_3.setText(_translate("MainWindow", "Wage"))
        self.driverWage.setText(_translate("MainWindow", "750 per week"))
        self.label_4.setText(_translate("MainWindow", "Licence"))
        self.licenceType.setText(_translate("MainWindow", "Abnormal"))
        self.label_5.setText(_translate("MainWindow", "Yard"))
        self.yardLocation.setText(_translate("MainWindow", "Tullamore"))
        self.label_6.setText(_translate("MainWindow", "Truck"))
        self.assignedTruck.setText(_translate("MainWindow", "Scania 770 (231 OY 123)"))
        self.label_7.setText(_translate("MainWindow", "Type"))
        self.typeComboBox.setItemText(0, _translate("MainWindow", "Fleet"))
        self.typeComboBox.setItemText(1, _translate("MainWindow", "Truck"))
        self.typeComboBox.setItemText(2, _translate("MainWindow", "Driver"))
        self.typeComboBox.setItemText(3, _translate("MainWindow", "Loaded"))
        self.availCheckBox.setText(_translate("MainWindow", "Available"))
        self.insertButton.setText(_translate("MainWindow", "Insert"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.prevButton.setText(_translate("MainWindow", "Prev"))
        self.assignLoadButton.setText(_translate("MainWindow", "Assign Load"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.trailerType.setText(_translate("MainWindow", "Trailer : Lowloader"))
        self.assignedLoad.setText(_translate("MainWindow", "Load : Crusher"))
        self.loadDestination.setText(_translate("MainWindow", "Destination : Dublin"))
        self.insertFromFileButton.setText(_translate("MainWindow", "Insert From FIle"))
        self.menuAdmin.setTitle(_translate("MainWindow", "Admin"))
        self.actionMark_Available.setText(_translate("MainWindow", "Mark Available"))
        self.actionMark_Unavailable.setText(_translate("MainWindow", "Mark Unavailable"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
